import React from 'react';
import { Head, Link } from '@inertiajs/react';
import AdminLayout from '@/Layouts/AdminLayout';
import { useTranslation } from '@/Hooks/useTranslation';
import { Award, Eye } from 'lucide-react';

interface Props {
    certificates: {
        data: Array<{
            id: number;
            uuid: string;
            certificate_code: string;
            student_name: string;
            student_email: string;
            course_title: string;
            issued_at: string;
        }>;
    };
}

export default function Index({ certificates }: Props) {
    const { t } = useTranslation();

    return (
        <AdminLayout title={t('admin.manage_certificates')}>
            <div className="space-y-6">
                <p className="text-xs text-slate-500">
                    Audit and inspect all verified certificates generated by students completing full courses.
                </p>

                <div className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-hidden shadow-xs">
                    <table className="w-full text-left text-xs">
                        <thead className="bg-slate-50 dark:bg-slate-800/60 border-b border-slate-200 dark:border-slate-800 text-slate-500 uppercase font-semibold">
                            <tr>
                                <th className="p-4">Certificate ID</th>
                                <th className="p-4">Student</th>
                                <th className="p-4">Course</th>
                                <th className="p-4">Issued At</th>
                                <th className="p-4 text-right">Verification Link</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                            {certificates.data.map((c) => (
                                <tr key={c.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40">
                                    <td className="p-4 font-mono font-bold text-emerald-600">
                                        {c.certificate_code}
                                    </td>
                                    <td className="p-4">
                                        <div className="font-bold text-slate-900 dark:text-white">
                                            {c.student_name}
                                        </div>
                                        <div className="text-slate-400 text-[11px]">{c.student_email}</div>
                                    </td>
                                    <td className="p-4 font-semibold text-slate-800 dark:text-slate-200">
                                        {c.course_title}
                                    </td>
                                    <td className="p-4 text-slate-500">{c.issued_at}</td>
                                    <td className="p-4 text-right">
                                        <Link
                                            href={`/certificates/${c.uuid}`}
                                            target="_blank"
                                            className="inline-flex items-center gap-1 px-3 py-1 bg-slate-100 dark:bg-slate-800 hover:bg-emerald-50 text-slate-700 dark:text-slate-200 rounded-lg text-xs font-semibold transition-colors"
                                        >
                                            <Eye className="w-3.5 h-3.5" />
                                            <span>View</span>
                                        </Link>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>
        </AdminLayout>
    );
}

